# Generated by Django 4.2.3 on 2023-07-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                ("unique_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=254)),
                ("scientific_name", models.CharField(max_length=254)),
                ("owner_name", models.CharField(max_length=150)),
                ("gender", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("contact", models.CharField(max_length=12)),
                ("address", models.TextField()),
            ],
        ),
    ]
